name: devn
favicon: null
layout_spectrum: 0.4502979915123433
typography_spectrum: 0.2921574234496802
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.48703206866048276
  lightness: 0.581183449132368
  saturation: 0.97869579680264
  rhythmicContrast: 0.6451196286361665
purpose: []
